/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "php_cpp_demo_constants.h"

namespace php_cpp_demo {

const php_cpp_demoConstants g_php_cpp_demo_constants;

php_cpp_demoConstants::php_cpp_demoConstants() {
}

} // namespace

