/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef php_cpp_demo_CONSTANTS_H
#define php_cpp_demo_CONSTANTS_H

#include "php_cpp_demo_types.h"

namespace php_cpp_demo {

class php_cpp_demoConstants {
 public:
  php_cpp_demoConstants();

};

extern const php_cpp_demoConstants g_php_cpp_demo_constants;

} // namespace

#endif
