/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef php_cpp_demo_TYPES_H
#define php_cpp_demo_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>


namespace php_cpp_demo {

struct ResponseState {
  enum type {
    StateOK = 0,
    StateError = 1,
    StateEmpty = 2
  };
};

extern const std::map<int, const char*> _ResponseState_VALUES_TO_NAMES;

class Request;

class Response;

typedef struct _Request__isset {
  _Request__isset() : studentID(true) {}
  bool studentID :1;
} _Request__isset;

class Request : public virtual ::apache::thrift::TBase {
 public:

  Request(const Request&);
  Request& operator=(const Request&);
  Request() : studentID(0) {
  }

  virtual ~Request() throw();
  int32_t studentID;

  _Request__isset __isset;

  void __set_studentID(const int32_t val);

  bool operator == (const Request & rhs) const
  {
    if (!(studentID == rhs.studentID))
      return false;
    return true;
  }
  bool operator != (const Request &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Request & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(Request &a, Request &b);

inline std::ostream& operator<<(std::ostream& out, const Request& obj)
{
  obj.printTo(out);
  return out;
}

typedef struct _Response__isset {
  _Response__isset() : studentID(true), name(false), infos(false), state(false) {}
  bool studentID :1;
  bool name :1;
  bool infos :1;
  bool state :1;
} _Response__isset;

class Response : public virtual ::apache::thrift::TBase {
 public:

  Response(const Response&);
  Response& operator=(const Response&);
  Response() : studentID(0), name(), state((ResponseState::type)0) {
  }

  virtual ~Response() throw();
  int32_t studentID;
  std::string name;
  std::vector<std::string>  infos;
  ResponseState::type state;

  _Response__isset __isset;

  void __set_studentID(const int32_t val);

  void __set_name(const std::string& val);

  void __set_infos(const std::vector<std::string> & val);

  void __set_state(const ResponseState::type val);

  bool operator == (const Response & rhs) const
  {
    if (!(studentID == rhs.studentID))
      return false;
    if (!(name == rhs.name))
      return false;
    if (!(infos == rhs.infos))
      return false;
    if (!(state == rhs.state))
      return false;
    return true;
  }
  bool operator != (const Response &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Response & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(Response &a, Response &b);

inline std::ostream& operator<<(std::ostream& out, const Response& obj)
{
  obj.printTo(out);
  return out;
}

} // namespace

#endif
